apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: code-pal-backend
  template:
    metadata:
      labels:
        app: code-pal-backend
    spec:
      containers:
      - name: code-pal-backend
        image: code-pal-backend:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
