apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: code-pal-frontend
  template:
    metadata:
      labels:
        app: code-pal-frontend
    spec:
      containers:
      - name: code-pal-frontend
        image: code-pal-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
